=== sriniGalway/OpenIoT/utils/utils.commons/src/main/resources/OSDSpec.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
     Copyright (c) 2011-2014, OpenIoT
     
     This file is part of OpenIoT.
 
     OpenIoT is free software: you can redistribute it and/or modify
     it under the terms of the GNU Lesser General Public License as published by
     the Free Software Foundation, version 3 of the License.

     OpenIoT is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU Lesser General Public License for more details.
 
     You should have received a copy of the GNU Lesser General Public License
     along with OpenIoT.  If not, see <http://www.gnu.org/licenses/>.
 
      Contact: OpenIoT mailto: info@openiot.eu
/ -->

<!-- Author: Nikos Kefalakis (nkef@ait.edu.gr) -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://www.openiot.eu/osdspec" xmlns:osd="http://www.openiot.eu/osdspec"
  xmlns:prt="http://www.w3.org/2007/SPARQL/protocol-types#">

  <xs:import namespace="http://www.w3.org/2007/SPARQL/protocol-types#"
    schemaLocation="sparql/protocol-types.xsd"/>

  <xs:element name="OSDSpec">
    <xs:annotation>
      <xs:documentation>OpenIoT Service Description Specification
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="osd:OAMO"/>
      </xs:sequence>
      <xs:attribute name="userID" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="OAMO">
    <xs:annotation>
      <xs:documentation>OpenIoT Application Model Object
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="osd:description"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="osd:graphMeta"/>
        <xs:element maxOccurs="unbounded" ref="osd:OSMO"/>
      </xs:sequence>
      <xs:attribute name="id" use="optional" type="xs:anyURI"/>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="graphMeta" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>

  <xs:element name="OSMO">
    <xs:annotation>
      <xs:documentation>OpenIoT Service Model Object</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="osd:description"/>
        <xs:element ref="osd:queryControls"/>
        <xs:element ref="osd:requestPresentation"/>
        <xs:sequence>
          <xs:element ref="prt:query-request" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" ref="osd:dynamicAttrMaxValue"/>
        </xs:sequence>
      </xs:sequence>
      <xs:attribute name="id" use="optional" type="xs:anyURI"/>
      <xs:attribute name="name" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="serviceID">
    <xs:complexType>
      <xs:sequence> </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="serviceName">
    <xs:complexType>
      <xs:sequence> </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="serviceDescription">
    <xs:complexType>
      <xs:sequence> </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="queryControls">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="osd:QuerySchedule"/>
        <xs:element name="trigger" type="xs:anyURI" minOccurs="0"/>
        <xs:element name="initialRecordTime" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="reportIfEmpty" type="xs:boolean"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="QuerySchedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="second" type="xs:string" minOccurs="0"/>
        <xs:element name="minute" type="xs:string" minOccurs="0"/>
        <xs:element name="hour" type="xs:string" minOccurs="0"/>
        <xs:element name="dayOfMonth" type="xs:string" minOccurs="0"/>
        <xs:element name="month" type="xs:string" minOccurs="0"/>
        <xs:element name="dayOfWeek" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="requestPresentation">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="osd:widget"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="widget">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="osd:presentationAttr"/>
      </xs:sequence>
      <xs:attribute name="widgetID" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="presentationAttr">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="dynamicAttrMaxValue">
    <xs:annotation>
      <xs:documentation>Maximum/Area of Interest for the defined dynamic
        value
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== sriniGalway/OpenIoT/utils/utils.commons/src/main/resources/OSDSpec/Samples/old-to-be-checked-Samples/OSDSpec_Sample1simple2.xml
<?xml version="1.0" encoding="UTF-8"?>
<osd:OSDSpec xmlns:res="http://www.w3.org/2007/SPARQL/results#"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:osd="urn:openiot:osdspec:xsd:1"
 xmlns:prt="http://www.w3.org/2007/SPARQL/protocol-types#"
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xsi:schemaLocation="urn:openiot:osdspec:xsd:1 file:/C:/Development/Eclipse_Worksp/Eclipse_Worksp4.2.2/OpenIoT/GitHub/ait-develop/openiot/utils/utils.commons/src/main/resources/OSDSpec.xsd" userID="nodeID://b46876">
    <osd:OAMO id="http://www.oxygenxml.com/" name="name0">
        <osd:description>description0</osd:description>
        <osd:graphMeta>><![CDATA[graphMeta0]]></osd:graphMeta>
        <osd:OSMO name="name1">
            <osd:description>description1</osd:description>
            <osd:queryControls>
                <osd:QuerySchedule>
                    <osd:second>second0</osd:second>
                    <osd:minute>minute0</osd:minute>
                    <osd:hour>hour0</osd:hour>
                    <osd:dayOfMonth>dayOfMonth0</osd:dayOfMonth>
                    <osd:month>month0</osd:month>
                    <osd:dayOfWeek>dayOfWeek0</osd:dayOfWeek>
                </osd:QuerySchedule>
                <osd:trigger>http://www.oxygenxml.com/</osd:trigger>
                <osd:initialRecordTime>2006-05-04T18:13:51.0Z</osd:initialRecordTime>
                <osd:reportIfEmpty>false</osd:reportIfEmpty>
            </osd:queryControls>
            <osd:requestPresentation>
                <osd:widget widgetID="nodeID://b44801">
                    <osd:presentationAttr name="name2" value="value0"/>
                </osd:widget>
            </osd:requestPresentation>
            <prt:query-request>
                <query><![CDATA[SELECT * FROM <peniot> WHERE {?s ?p ?o}]]></query>
                <default-graph-uri>http://www.oxygenxml.com/</default-graph-uri>
                <named-graph-uri>http://www.oxygenxml.com/</named-graph-uri>
            </prt:query-request>
            <osd:dynamicAttrMaxValue name="name3" value="value1"/>
        </osd:OSMO>
    </osd:OAMO>
</osd:OSDSpec>

=== sriniGalway/OpenIoT/utils/utils.commons/src/main/resources/OSDSpec/Samples/old-to-be-checked-Samples/OSDSpec_Sample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<osd:OSDSpec xmlns:res="http://www.w3.org/2007/SPARQL/results#"
 xmlns:osd="urn:openiot:osdspec:xsd:1"
 xmlns:prt="http://www.w3.org/2007/SPARQL/protocol-types#"
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:openiot:osdspec:xsd:1 file:/C:/Development/Eclipse_Worksp/Eclipse_Worksp4.2.2/OpenIoT/GitHub/ait-develop/openiot/utils/utils.commons/src/main/resources/OSDSpec.xsd" userID="nodeID://b46876">
    <osd:OAMO id="OpenIoTApplicationModelObject1ID" name="OpenIoTApplicationModelObject1Name">
        <osd:description>OpenIoTApplicationModelObject1Descreption</osd:description>
        <osd:graphMeta>><![CDATA[Here You Will Adde The Request Definition Meta Data]]></osd:graphMeta>
        <osd:OSMO id="http://www.oxygenxml.com/" name="only_one_oamo_test_osmo_name">
            <osd:description>only one oamo test osmo_description</osd:description>
            <osd:queryControls>
                <osd:QuerySchedule>
                    <osd:second>second0</osd:second>
                    <osd:minute>minute0</osd:minute>
                    <osd:hour>hour0</osd:hour>
                    <osd:dayOfMonth>dayOfMonth0</osd:dayOfMonth>
                    <osd:month>month0</osd:month>
                    <osd:dayOfWeek>dayOfWeek0</osd:dayOfWeek>
                </osd:QuerySchedule>
                <osd:trigger>http://www.triger.com/</osd:trigger>
                <osd:initialRecordTime>2006-05-04T18:13:51.0Z</osd:initialRecordTime>
                <osd:reportIfEmpty>true</osd:reportIfEmpty>
            </osd:queryControls>
            <osd:requestPresentation>
                <osd:widget widgetID="nodeID://b44801">
                    <osd:presentationAttr name="widget b44801 attr1" value="widget b44801 value1"/>
					<osd:presentationAttr name="widget b44801 attr2" value="widget b44801 value2"/>
                </osd:widget>
				<osd:widget widgetID="nodeID://b44790">
                    <osd:presentationAttr name="widget b44790 attr1" value="widget b44790 value1"/>
					<osd:presentationAttr name="widget b44790 attr2" value="widget b44790 value2"/>
                </osd:widget>
            </osd:requestPresentation>
            <prt:query-request>
                <query><![CDATA[SELECT * FROM <peniot> WHERE {?s ?p ?o}]]></query>
                <default-graph-uri>http://www.default-graph-uri.com/</default-graph-uri>
                <named-graph-uri>http://www.named-graph-uri.com/</named-graph-uri>
            </prt:query-request>
            <osd:dynamicAttrMaxValue name="name1" value="valueofname1"/>
			<osd:dynamicAttrMaxValue name="name2" value="valueofname2"/>
			<osd:dynamicAttrMaxValue name="name3" value="valueofname3"/>
			<osd:dynamicAttrMaxValue name="name4" value="valueofname4"/>
        </osd:OSMO>
    </osd:OAMO>
</osd:OSDSpec>

=== sriniGalway/OpenIoT/utils/utils.commons/src/main/resources/OSDSpec/Samples/old-to-be-checked-Samples/OSDSpec_SimpleSample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<OSDSpec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:/C:/Development/Eclipse_Worksp/Eclipse_Worksp4.2.2/OpenIoT/GitHub/ait-develop/openiot/utils/openIotCommons/src/main/resources/OSDSpec/OSDSpec.xsd"
	userID="nodeID://b46876">
	<OAMO id="OpenIoTApplicationModelObject1ID" name="OpenIoTApplicationModelObject1Name">
		<description>OpenIoTApplicationModelObject1Descreption</description>
		<OSMO name="only one oamo test osmo_name">
			<description>only one oamo test osmo_description</description>
			<queryControls>
				<QuerySchedule>
					<second>M9y7aLQSxSj3s-NiLVNoDgz</second>
					<minute>vuL0v.3s_jsB</minute>
					<hour>qbBht_g</hour>
					<dayOfMonth>K5dKF-Vki7X</dayOfMonth>
					<month>CZw9WuVoztWeN1lV7Q-rOckNZR</month>
					<dayOfWeek>Yvz_omXZU7yTpPa1V8NiSqaL</dayOfWeek>
				</QuerySchedule>
				<trigger>http://vyfDxLWN/</trigger>
				<initialRecordTime>2013-11-20T22:54:08</initialRecordTime>
				<reportIfEmpty>true</reportIfEmpty>
			</queryControls>
			<requestPresentation>
				<widget widgetID="nodeID://b44801">
					<presentationAttr name="widget b44801 attr1"
						value="widget b44801 value1 " />
					<presentationAttr name="widget b44801 attr2"
						value="widget b44801 value2" />
				</widget>
				<widget widgetID="nodeID://b44790">
					<presentationAttr name="widget b44790 attr1"
						value="widget b44790 value1" />
					<presentationAttr name="widget b44790 attr2"
						value="widget b44790 value2" />
				</widget>
			</requestPresentation>
			<query-request>
				<query>SELECT * FROM #openiot# WHERE {?s ?p ?o}</query>
				<default-graph-uri>http://AaQuDPSJ/</default-graph-uri>
				<named-graph-uri>http://kHGZizGZ/</named-graph-uri>
				<dynamicAttrMaxValue name="HMIJ_yAks5E"
					value="_kKKOBxL4fMVWVN.yW0CM0v" />
				<dynamicAttrMaxValue name="JEOs6Rt"
					value="P4yO.t2R0ky5V2Vo9shr-dkgC" />
				<dynamicAttrMaxValue name="khsITns1Dj.m5Di.c"
					value="dizQ.h2cLctlMQuB7tAEBpmxWi" />
			</query-request>
		</OSMO>
	</OAMO>
</OSDSpec>

=== sriniGalway/OpenIoT/utils/utils.commons/src/main/resources/OSDSpec/Samples/old-to-be-checked-Samples/OSDSpec_SimpleSample3.xml
<?xml version="1.0" encoding="UTF-8"?>
<OSDSpec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:/C:/Development/Eclipse_Worksp/Eclipse_Worksp4.2.2/OpenIoT/GitHub/ait-develop/openiot/utils/openIotCommons/src/main/resources/OSDSpec/OSDSpec.xsd"
	userID="nodeID://b46876">
	<OAMO id="oamo_test_1" name="oamo_name_1">
		<description>oamo test 1 description</description>
		<OSMO name="osmo test service 1">
			<description>osmo test service description 1</description>			
			<requestPresentation>
				<widget widgetID="nodeID://b44801">
					<presentationAttr name="widget b44801 attr1"
						value="widget b44801 value1 " />
					<presentationAttr name="widget b44801 attr2"
						value="widget b44801 value2" />
				</widget>
				<widget widgetID="nodeID://b44790">
					<presentationAttr name="widget b44790 attr1"
						value="widget b44790 value1" />
					<presentationAttr name="widget b44790 attr2"
						value="widget b44790 value2" />
				</widget>
			</requestPresentation>
			<query-request>
				<query>SELECT * FROM #openiot# WHERE {?s ?p ?o}</query>
				<default-graph-uri>http://AaQuDPSJ/</default-graph-uri>
				<named-graph-uri>http://kHGZizGZ/</named-graph-uri>
				<dynamicAttrMaxValue name="HMIJ_yAks5E"
					value="_kKKOBxL4fMVWVN.yW0CM0v" />
				<dynamicAttrMaxValue name="JEOs6Rt"
					value="P4yO.t2R0ky5V2Vo9shr-dkgC" />
				<dynamicAttrMaxValue name="khsITns1Dj.m5Di.c"
					value="dizQ.h2cLctlMQuB7tAEBpmxWi" />
			</query-request>
		</OSMO>
	</OAMO>
	<OAMO id="oamo_test_2" name="oamo_desc_2">
		<description>oamo test 2 description</description>
		<OSMO name="osmo test service 2">
			<description>osmo test service description 2</description>			
			<requestPresentation>
				<widget widgetID="nodeID://b44801">
					<presentationAttr name="widget b44801 attr1"
						value="widget b44801 value1 " />
					<presentationAttr name="widget b44801 attr2"
						value="widget b44801 value2" />
				</widget>
				<widget widgetID="nodeID://b44790">
					<presentationAttr name="widget b44790 attr1"
						value="widget b44790 value1" />
					<presentationAttr name="widget b44790 attr2"
						value="widget b44790 value2" />
				</widget>
				<widget widgetID="nodeID://b44789">
					<presentationAttr name="widget b44789 attr1"
						value="widget b44789 value1" />
					<presentationAttr name="widget b44789 attr2"
						value="widget b44789 value2" />
					<presentationAttr name="widget b44789 attr3"
						value="widget b44789 value3" />
				</widget>
			</requestPresentation>
			<query-request>
				<query>SELECT * FROM #openiot# WHERE {?s ?p ?o}</query>
				<default-graph-uri>http://AaQuDPSJ/</default-graph-uri>
				<named-graph-uri>http://kHGZizGZ/</named-graph-uri>
				<dynamicAttrMaxValue name="HMIJ_yAks5E"
					value="_kKKOBxL4fMVWVN.yW0CM0v" />
				<dynamicAttrMaxValue name="JEOs6Rt"
					value="P4yO.t2R0ky5V2Vo9shr-dkgC" />
				<dynamicAttrMaxValue name="khsITns1Dj.m5Di.c"
					value="dizQ.h2cLctlMQuB7tAEBpmxWi" />
			</query-request>
		</OSMO>
	</OAMO>
	
</OSDSpec>

=== sriniGalway/OpenIoT/utils/utils.commons/src/main/resources/OSDSpec/Samples/old-to-be-checked-Samples/OSDSpec_SimpleSample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<OSDSpec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:/C:/Development/Eclipse_Worksp/Eclipse_Worksp4.2.2/OpenIoT/GitHub/ait-develop/openiot/utils/openIotCommons/src/main/resources/OSDSpec/OSDSpec.xsd"
	userID="nodeID://b46876">
	<OAMO id="OpenIoTApplicationModelObject1ID" name="OpenIoTApplicationModelObject1Name">
		<description>OpenIoTApplicationModelObject1Descreption</description>
		<OSMO id="http://SensorModelObject1ServiceID/" name="SensorModelObject1Name">
			<description>OpenIoT Sensor Model Object 1</description>
			<queryControls>
				<QuerySchedule>
					<second>M9y7aLQSxSj3s-NiLVNoDgz</second>
					<minute>vuL0v.3s_jsB</minute>
					<hour>qbBht_g</hour>
					<dayOfMonth>K5dKF-Vki7X</dayOfMonth>
					<month>CZw9WuVoztWeN1lV7Q-rOckNZR</month>
					<dayOfWeek>Yvz_omXZU7yTpPa1V8NiSqaL</dayOfWeek>
				</QuerySchedule>
				<trigger>http://vyfDxLWN/</trigger>
				<initialRecordTime>2013-11-20T22:54:08</initialRecordTime>
				<reportIfEmpty>true</reportIfEmpty>
			</queryControls>
			<requestPresentation>
				<widget widgetID="http://TheYperwidgetID/">
					<presentationAttr name="widget1PresentationAttr1Name"
						value="widget1PresentationAttr1Value" />
					<presentationAttr name="widget1PresentationAttr2Name"
						value="widget1PresentationAttr2Value" />
				</widget>
				<widget widgetID="http://TheYperwidget2ID/">
					<presentationAttr name="widget2PresentationAttr1Name"
						value="widget2PresentationAttr1Value" />
					<presentationAttr name="widget2PresentationAttr2Name"
						value="widget2PresentationAttr2Value" />
				</widget>
			</requestPresentation>
			<query-request>
				<query>SELECT * FROM #openiot# WHERE {?s ?p ?o}</query>
				<default-graph-uri>http://AaQuDPSJ/</default-graph-uri>
				<named-graph-uri>http://kHGZizGZ/</named-graph-uri>
				<dynamicAttrMaxValue name="HMIJ_yAks5E"
					value="_kKKOBxL4fMVWVN.yW0CM0v" />
				<dynamicAttrMaxValue name="JEOs6Rt"
					value="P4yO.t2R0ky5V2Vo9shr-dkgC" />
				<dynamicAttrMaxValue name="khsITns1Dj.m5Di.c"
					value="dizQ.h2cLctlMQuB7tAEBpmxWi" />
			</query-request>
		</OSMO>
	</OAMO>
</OSDSpec>
